### ISSUE TITLE
Gzip event response images if accept encoding matches

### ISSUE THREAD

**Issue by solocommand** [cygnusb2b/fortnight-graph#95]
Will reduce transmitted size of the image over the wire

**Comment by zarathustra323** [comment]
@solocommand Was this handled in Rancher/Nginx at all?

**Comment by solocommand** [comment]
@zarathustra323 no

**Comment by solocommand** [comment]
It's hitting node/express directly from the load balancer, IMO express should do it

**Comment by zarathustra323** [comment]
Express recommends to NOT do it on the node side.

Sent from my iPhone

On Jun 12, 2018, at 12:28, Josh Worden <notifications@github.com<mailto:notifications@github.com>> wrote:


It's hitting node/express directly from the load balancer, IMO express should do it
